'use strict';

const lib = require('lib');
describe('lib', ()=> {
  describe('logic', ()=> {
    it('test', () => {
      expect(lib.logic.buildEsasParam({
        index                    : 1,
        channel                  : 0,
        startPosSec              : 1.12,
        endPosSec                : 1.6,
        validSegment             : true,
        energy                   : 29,
        joy                      : 0,
        sad                      : 0,
        aggression               : 0,
        stress                   : 1,
        uncertainty              : 15,
        excitement               : 25,
        uneasy                   : 0,
        concentration            : 0,
        anticipation             : 0,
        hesitation               : 11,
        emotionBalance           : 67,
        emotionEnergyBalance     : 1015,
        mentalEffort             : 9,
        imagination              : 0,
        arousal                  : 0,
        overallCognitiveActivity : 1160,
        emotionCognitiveRatio    : 150,
        extremeEmotion           : 5,
        atmosphere               : 7,
        voiceEnergy              : 187,
        dissatisfied             : 0,
        'EDP-Energetic'          : 58,
        'EDP-Passionate'         : 1,
        'EDP-Emotional'          : 96,
        'EDP-Uneasy'             : 83,
        'EDP-Stressful'          : 18,
        'EDP-Thoughtful'         : 33,
        'EDP-Confident'          : 80,
        'EDP-Concentrated'       : 2,
        'EDP-Anticipation'       : 16,
        'EDP-Hesitation'         : 22,
        callPriority             : -1,
        callPriorityAgent        : -1,
        VOL1                     : 9382,
        VOL2                     : 122,
        SOS                      : 60,
        AVJ                      : 532,
        Fant                     : 10,
        Fflic                    : 4,
        Fmain                    : 18,
        JQ                       : 11,
        LJ                       : 1,
        SPJ                      : 145,
        SPT                      : 1015,
        intCHL                   : 2901
      })).to.deep.equals({
        // startTime: '',
        Channel: 0,
        StartPosSec: 1.12,
        EndPosSec: 1.6,
        Energy: 58,
        Stress: 2,
        'EMO/COG': 150,
        Concentration: 0,
        Anticipation: 0,
        Excitement: 25,
        Hesitation: 11,
        Uncertainty: 15,
        IntensiveThinking: 29,
        ImaginationActivity: 0,
        Embarrassment: 0,
        Passionate: 0,
        BrainPower: 58,
        Confidence: 15,
        Aggression: 0,
        CallPriority: 0,
        AgentScore: 0,
        Atmosphere: 7,
        Upset: 0,
        Content: 0,
        Dissatisfaction: 0,
        ExtremeEmotion: 5
      })
    });
  });
});
